name: Update Release Notes
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_RELEASE_NOTES_TOKEN }}

    steps:

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          ignorePreReleases: true
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "pr_template": "- #{{TITLE}}\n- ##{{BODY}}",
              "commit_template": "- #{{TITLE}}\n- ##{{BODY}}",
              "categories": [
                {
                    "title": "## ‚ûï New",
                    "labels": ["new"]
                },
                {
                    "title": "## ‚ùå Removed",
                    "labels": ["removed", "deleted", "rem", "del"]
                },
                {
                    "title": "## ‚úÖ Bugfixes",
                    "labels": ["fix", "bug", "bugfix",]
                },
                {
                    "title": "## üíÄ Deprecated",
                    "labels": ["deprecated", "depr"]
                },
                {
                    "title": "## üì¶ Dependencies",
                    "labels": ["dependencies", "dep"]
                },
                {
                    "title": "## ‚úèÔ∏è Changes",
                    "labels": ["change"]
                },
                {
                    "title": "## üìù Documentation",
                    "labels": ["docs", "documentation"]
                },
                {
                    "title": "## üß™ Tests",
                    "labels": ["test"]
                },
                {
                    "title": "## üé® UI",
                    "labels": ["ui", "design"]
                },
                {
                    "title": "## ‚öôÔ∏è Build",
                    "labels": ["build", "ci", "cd"]
                },
                {
                    "title": "## Others",
                    "labels": [""]
                }
              ],
              "transformers": [
                {
                    "name": "MULTI LINE TRANSFORMER",
                    "source": "BODY",
                    "transformer": {
                        "pattern": "(.*[^\\r\\n)])+",
                        "method": "regexr",
                        "target": '- $1'
                    }
                }
              ]
            }

      - name: Create Release X
        uses: mikepenz/action-gh-release@v0.2.0-a03
        with:
          body: ${{steps.github_release.outputs.changelog}}